/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InfoPanel.java
 *
 * Created on 05.02.2010, 09:24:44
 */

package moa.gui.visualization;

import javax.swing.JFrame;

/**
 *
 * @author jansen
 */
public class InfoPanel extends javax.swing.JPanel {

    private JFrame infoFrame = null;

    /** Creates new form InfoPanel */
    public InfoPanel(JFrame infoFrame) {
        this.infoFrame = infoFrame;
        initComponents();
    }

    public void updateInfo(String text){
        infoFrame.setVisible(true);
        jTextPane1.setText(text);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPane1 = new javax.swing.JTextPane();

        setLayout(new java.awt.GridLayout(1, 0));

        jTextPane1.setEditable(false);
        add(jTextPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
