build-latest:
	    docker build -t waikato/moa:latest -f moa-gui.Dockerfile .
build-devel:
	    docker build -t waikato/moa:devel -f devel-gui.Dockerfile .
push-latest:
	    docker push waikato/moa:latest
push-devel:
	    docker push waikato/moa:devel