build-latest:
	    docker build --no-cache -t ghcr.io/waikato/moa:latest -f moa-gui.Dockerfile .
build-devel:
	    docker build --no-cache -t ghcr.io/waikato/moa:devel -f devel-gui.Dockerfile .
push-latest:
	    docker push ghcr.io/waikato/moa:latest
push-devel:
	    docker push ghcr.io/waikato/moa:devel